version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "lists3-nodejs14x"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-6idfyhk5n80d"
s3_prefix = "lists3-nodejs14x"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = ["HelloWorldFunction=737367569205.dkr.ecr.us-east-1.amazonaws.com/jikko"]
